### ISSUE TITLE
ENOTDIR ajaxim error

### ISSUE THREAD

**Issue by muthiafi** [endtwist/AjaxIM#37]
hey i dont know whats wrong 
i already follow all the instruction
and everything seems to run fine
i able to set the cookies on /dev/cookie
but when on /dev/
i got this ENOTDIR error

127.0.0.1 - - [Wed, 10 Nov 2010 04:21:59 GMT] "GET /js/jquery.jsonp-1.1.3.min.js
 HTTP/1.1" 500 - "http://localhost:8000/dev/" "Mozilla/5.0 (Windows; U; Windows
NT 6.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/53
4.7"
Error: ENOTDIR, Not a directory '/home/mufi/endtwist-AjaxIM-3d667cf/server/dev/p
ublic/js/im.js'

any clues on what happen?
it seems it cannot load all the file needed >.<

**Comment by endtwist** [comment]
Fixed: https://github.com/endtwist/AjaxIM/commit/263b00b5cd87adefb2421a8290ea432a809111dd
