### ISSUE TITLE
Friends list does not get updated for previously logged in users.

### ISSUE THREAD

**Issue by paulm17** [endtwist/AjaxIM#39]
What happens is this:

Lets say UserA logs into the site and has 0 friends logged in.

UserB logs in and is friends with UserA.  UserB will have UserA in its
friends list, but UserA's own friends list will not be refreshed.

The only way to refresh UserA's own list is to log in and log out
again, but this defeats the purpose.

Also, in the same example lets say UserA and UserB both see each
other.  When UserB logs off, UserA gets no notification and can still
chat to UserB.

**Comment by pjriot** [comment]
```
diff --git a/client/js/im.js b/client/js/im.js
index c8ec043..8c19470 100644
--- a/client/js/im.js
+++ b/client/js/im.js
@@ -412,6 +412,7 @@ $.extend(AjaxIM.prototype, {
                 this.current_status = ['available', ''];
                 store.set('user', message.username);
                 store.set(this.username + '-status', this.current_status);
+               self.status('available', '');

                 $('#imjs-friends').attr('class', 'imjs-available');
                 $.each(message.friends, function() {
@@ -952,7 +953,7 @@ $.extend(AjaxIM.prototype, {
     // the update to all individuals with "you" on their friends list.
     //
     // ==== Parameters ====
-    // * {{{s}}} is the status code, as defined by {{{AjaxIM.statuses}}}.
+    // * {{{value}}} is the status code, as defined by {{{AjaxIM.statuses}}}.
     // * {{{message}}} is the custom status message.
     status: function(value, message) {
         var self = this;
```

**Comment by pjriot** [comment]
This seems to solve the problem, although I'm not sure its the correct fix. I'd love to hear Joshua's comments.

**Comment by endtwist** [comment]
It would be nicer to do it from the server (when the 'hello' action occurs, notify other users), but this client-side fix works in lieu of a better option. Let's look into sending it from the server, first, however.

**Comment by paulm17** [comment]
Agreed, however we couldn't find a way to do this.  

We have noticed that although this.events.addListener('update',o_.bind(session.receivedUpdate, session)); should get fired when a user auth's, it currently doesn't.  If it did, this would resolve the issue.

**Comment by pjriot** [comment]
Well, its not impossible. Its just that there's a lot of code in the client side around calling self.status(). It seemed a lot easier to just call it here in the client as opposed to changing that around.

**Comment by paulm17** [comment]
```
diff --git a/hub.js b/hub_old.js
old mode 100755
new mode 100644
index 50bed28..8fb722a
--- a/hub.js
+++ b/hub_old.js
@@ -69,9 +69,8 @@ Hub.prototype.get = function(req, fn) {
                                             [username, friend.status()];
                     }, this);

-                    session._friends(friends_copy);                   
-                    
-                   session.events.addListener('status',
+                    session._friends(friends_copy);
+                    session.events.addListener('status',
                         o_.bind(function(value, message) {
                             this.events.emit(
                                 'update',
@@ -80,14 +79,8 @@ Hub.prototype.get = function(req, fn) {
                                                     message)
                             );
                         }, this));
-                        
-                                                                         
-                        
-                     this.events.addListener('update',
+                    this.events.addListener('update',
                                       o_.bind(session.receivedUpdate, session))
-                                      
-                      session.status('available', '');
-                                                                            
                     this.set(req.sessionID, session);
                     fn(null, session);
                 }, this));                         
```

However, this is a crappy solution as it does a broadcast to all users, irrespective if they are on your friends list or not.

There needs to be a better solution where it takes the friends list from the user after auth, checks which users are online and then sends an actual notification to each user.

To be honest, this ties into the initiating and accepting of friend requests: 
- having notifications if the user is online
- notifications to the receipient 
- addition to the friendlist for the user who accepts
- addition to the friendlist if the initiator is online

IOW a notifications system needs to be built so that any notification can be sent from ajaxim and then handled in the clientside.

**Comment by endtwist** [comment]
When `.status` is called on the hub, it gets sent out as an event and each client checks if that user is in their friends list (in `receivedUpdate`), right now. So that solution works, however, I agree that we need a better way distribute notifications to the relevant sets of users.

In the meantime, perhaps we should push your fix, Paul, and then work from there?

**Comment by paulm17** [comment]
pjriot has made some changes with respect to the sessions.  I am testing this now.  I think we should invest time in developing a notification system.  Once this has been implemented and tested then it should be best to do a push and go from there.
