### ISSUE TITLE
Name in IM title bar does not get refreshed after different user login

### ISSUE THREAD

**Issue by paulm17** [endtwist/AjaxIM#41]
User A logs in and IM title bar says "Peter".  User A logs out.

User B logs into same machine and title bar still says "Peter", although json data has correct information pertaining to User B.

Note: A browser refresh does solve this problem.

**Comment by paulm17** [comment]
fix suggestion:

find: 

// Set username in Friends list

var header = $('#imjs-friends-panel .imjs-header');
header.html(header.html().replace('{username}', this.username));

replace last line with:

header.html(this.username);

**Comment by endtwist** [comment]
You'll need to select the <span> inside .imjs-header:

```
var header = $('#imjs-friends-panel .imjs-header');
header.find('span').html(this.username);
```

Something like that, so that it doesn't overwrite the minimize button.
