### ISSUE TITLE
No login function in im.js

### ISSUE THREAD

**Issue by checkelmann** [endtwist/AjaxIM#45]
Hi,

I'm currently trying to get ajaxim (latest from git) running with node server. There is no login (or) logout function in the current im.js.
How do i authenticate now?

Regards,

Christian

**Comment by endtwist** [comment]
Ajax IM is intended to tie in with your existing authentication and session system. It does not need login or logout functionality.

If you have a question in the future, please use the discussion boards at http://groups.google.com/group/ajaxim
