### ISSUE TITLE
AjaxIM.init is not a function

### ISSUE THREAD

**Issue by didacrios** [endtwist/AjaxIM#5]
This is what it shows firebug when i load a page that contains the "registration form"

```
<div id="ajaxim">
 <script type="text/javascript">
    AjaxIM.loaded(function() { AjaxIM.client.form('#ajaxim'); }); // Line 233 !!!
 </script>
</div>
```

AjaxIM.init is not a function
im.load.js?php
Line 50

AjaxIM.init is not a function
init()im.load.js?php (line 50)
loadDep()im.load.js?php (line 29)
nextdep()im.load.js?php (line 37)
[Break on this error] flashStorage: jsfolder + 'jStore.Flash.html'

**Comment by endtwist** [comment]
Try moving the script tag _outside_ of the div element.

e.g.:
    <div id="ajaxim"></div>
    <script type="text/javascript">
        AjaxIM.loaded(function() { AjaxIM.client.form('#ajaxim'); }); // Line 233 !!!
    </script>

Let me know if that works.

**Comment by didacrios** [comment]
no changes, exactly the same problem
