### ISSUE TITLE
How to add a new friend in the DB

### ISSUE THREAD

**Issue by nodapio** [endtwist/AjaxIM#53]
Hi,
I want to add a new user in the friend list of someone with a MySQL query, but i don't understand how the friend management system works, and the menu "Database Backends" is not available on the official website.

Help would be greatly appreciated ;) Thanks.

**Comment by ajaximrpg** [comment]
In the latest code of the "master" branch in the "dev" environment, friends are not stored in a DB; they are hardcoded in AjaxIM / server / libs / authentication / default / index.js.  Friends are accessed using the exports.friends() function.

If that doesn't answer your question, please reopen this issue or post a new one.
