### ISSUE TITLE
node.js version?

### ISSUE THREAD

**Issue by udi111** [endtwist/AjaxIM#6]
which version of node.js should be used?
because i see major changes in the changelog of it.

i installed 0.1.18 (as suggested on ajaxim homepage), on startup it sends this message: (evcom) bind() Cannot assign requested address.
after a successful connection (User connected blah blah) communication stops, and i cannot connect again until i delete the cookie from the browser.
i use the latest version of ajaxim downloaded from here.

**Comment by udi111** [comment]
the (evcom) bind() message disappeared when i changed the hostname but it still doesn't want to keep the connection alive :)

**Comment by endtwist** [comment]
Try the latest version of Node.js, and pull the latest server.js from the repo. I've just merged an update from "loe" that should let the server work properly with the latest Node.js version.
